/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './landing.html',
    './politicas-privacidad.html',
    './politicas-seguridad.html',
    './src/**/*.{astro,js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'oklch(var(--background) / <alpha-value>)',
        foreground: 'oklch(var(--foreground) / <alpha-value>)',
        card: 'oklch(var(--card) / <alpha-value>)',
        'card-foreground': 'oklch(var(--card-foreground) / <alpha-value>)',
        popover: 'oklch(var(--popover) / <alpha-value>)',
        'popover-foreground': 'oklch(var(--popover-foreground) / <alpha-value>)',
        primary: {
          DEFAULT: 'oklch(var(--primary) / <alpha-value>)',
          foreground: 'oklch(var(--primary-foreground) / <alpha-value>)',
          50: 'oklch(var(--primary-50) / <alpha-value>)',
          100: 'oklch(var(--primary-100) / <alpha-value>)',
          200: 'oklch(var(--primary-200) / <alpha-value>)',
          300: 'oklch(var(--primary-300) / <alpha-value>)',
          400: 'oklch(var(--primary-400) / <alpha-value>)',
          500: 'oklch(var(--primary-500) / <alpha-value>)',
          600: 'oklch(var(--primary-600) / <alpha-value>)',
          700: 'oklch(var(--primary-700) / <alpha-value>)',
          800: 'oklch(var(--primary-800) / <alpha-value>)',
          900: 'oklch(var(--primary-900) / <alpha-value>)',
          950: 'oklch(var(--primary-950) / <alpha-value>)',
        },
        'primary-foreground': 'oklch(var(--primary-foreground) / <alpha-value>)',
        'primary-dark': 'oklch(var(--primary-dark) / <alpha-value>)',
        secondary: {
          DEFAULT: 'oklch(var(--secondary) / <alpha-value>)',
          foreground: 'oklch(var(--secondary-foreground) / <alpha-value>)',
        },
        'secondary-foreground': 'oklch(var(--secondary-foreground) / <alpha-value>)',
        muted: {
          DEFAULT: 'oklch(var(--muted) / <alpha-value>)',
          foreground: 'oklch(var(--muted-foreground) / <alpha-value>)',
        },
        'muted-foreground': 'oklch(var(--muted-foreground) / <alpha-value>)',
        accent: {
          DEFAULT: 'oklch(var(--accent) / <alpha-value>)',
          foreground: 'oklch(var(--accent-foreground) / <alpha-value>)',
        },
        'accent-2': 'var(--color-accent-2)',
        'accent-foreground': 'oklch(var(--accent-foreground) / <alpha-value>)',
        border: 'oklch(var(--border) / <alpha-value>)',
        input: 'oklch(var(--input) / <alpha-value>)',
        ring: 'oklch(var(--ring) / <alpha-value>)',
        destructive: {
          DEFAULT: 'oklch(var(--destructive) / <alpha-value>)',
          foreground: 'oklch(var(--destructive-foreground) / <alpha-value>)',
        },
        'destructive-foreground': 'oklch(var(--destructive-foreground) / <alpha-value>)',
        success: 'oklch(var(--success) / <alpha-value>)',
        'night-paper': 'var(--color-night-paper)',
        'night-ink': 'var(--color-night-ink)',
        tool: {
          background: '#0d1f0e',
          surface: '#1a3d1f',
          border: '#2d6b35',
          primary: '#3d8c47',
          accent: '#5aad62',
          highlight: '#7ecf86',
          'text-dark': '#b4e8b8',
          'text-light': '#e0f5e2',
        },
      },
      fontFamily: {
        sans: ['Manrope', 'system-ui', 'sans-serif'],
        display: ['Manrope', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        /* Lumen (home page only) — applied via .lumen scope, not the site-wide defaults above */
        'lumen-display': ['"Instrument Serif"', '"Tiempos Headline"', 'ui-serif', 'Georgia', 'serif'],
        'lumen-body': ['"Geist"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'lumen-card': '20px',
      },
    },
  },
  plugins: [],
}
